# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82433d91e2349d0d8bb2c3b0ba0d6193290fcfe93bbc7cf0276f559a4483e216994ceb80676090adfe1fbcfc6e9c7efedd1e11bd076c13112872b5e8fbb5dd7b

test:
  secret_key_base: 3b3d8db90eb0b5a6b701bb2dca156cbb5a7389000f0d4998f23f6c97af272bbe9d39aaa8715d49d6e2176219b9b2daa49033a8c0c34e9edd24ba46b73965594f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
